analogue_interiors_blog/analogue_interiors_blog/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include(('projects.urls', 'projects'), namespace='projects'))
]

analogue_interiors_blog/projects/urls.py
from django.urls import path
from projects.views import ProjectListView, ProjectDetailView, ProjectCreateView, ProjectUpdateView, ProjectDeleteView

app_name = 'projects'

urlpatterns = [
    path('', ProjectListView.as_view(), name='list'),
    path('project/<int:pk>/', ProjectDetailView.as_view(), name='detail'),
    path('project/new/', ProjectCreateView.as_view(), name='new'),
    path('project/<int:pk>/edit/', ProjectUpdateView.as_view(), name='edit'),
    path('project/<int:pk>/delete/',
         ProjectDeleteView.as_view(), name='delete')
]

analogue_interiors_blog/projects/models.py
from django.db import models
from django.urls import reverse


class Project(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    date_added = models.DateTimeField(auto_now=True)
    date_modified = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('projects:detail', kwargs={'pk': self.pk})

analogue_interiors_blog/projects/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from projects.models import Project


class ProjectListView(ListView):
    model = Project
    template_name = 'projects/project_list.html'
    context_object_name = 'projects'


class ProjectDetailView(DetailView):
    model = Project
    template_name = 'projects/project_detail.html'


class ProjectCreateView(CreateView):
    model = Project
    template_name = 'projects/project_form.html'
    fields = ['name', 'description']


class ProjectUpdateView(UpdateView):
    model = Project
    template_name = 'projects/project_form.html'
    fields = ['name', 'description']


class ProjectDeleteView(DeleteView):
    model = Project
    template_name = 'projects/project_confirm_delete.html'
    success_url = reverse_lazy('projects:list')

analogue_interiors_blog/analogue_interiors_blog/templates/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html>
    <head>
        <title>My projects</title>
        {% bootstrap_css %}
        {% bootstrap_javascript jquery='full' %}
    </head>
    <body>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

analogue_interiors_blog/analogue_interiors_blog/templates/projects/project_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Project</h1>

  <p>Are you sure you want to delete the project "{{ project.name }}"?</p>

  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Confirm Delete</button>
  </form>

  <a href="{% url 'projects:list' %}" class="btn btn-secondary mt-3">Cancel</a>
{% endblock %}

analogue_interiors_blog/analogue_interiors_blog/templates/projects/project_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Project Details</h1>

  <div class="card">
    <div class="card-body">
      <h5 class="card-title">{{ project.name }}</h5>
      <p class="card-text">{{ project.description }}</p>
      <a href="{% url 'projects:edit' project.id %}" class="btn btn-primary">Edit</a>
      <a href="{% url 'projects:delete' project.id %}" class="btn btn-danger">Delete</a>
    </div>
  </div>

  <a href="{% url 'projects:list' %}" class="btn btn-secondary mt-3">Back to Projects</a>
{% endblock %}

analogue_interiors_blog/analogue_interiors_blog/templates/projects/project_form.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
  <h1>New Project</h1>

  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-primary">Save</button>
  </form>

  <a href="{% url 'projects:list' %}" class="btn btn-secondary mt-3">Cancel</a>
{% endblock %}

analogue_interiors_blog/analogue_interiors_blog/templates/projects/project_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Projects</h1>

  {% for project in projects %}
    <div class="card mb-3">
      <div class="card-body">
        <h5 class="card-title">{{ project.name }}</h5>
        <p class="card-text">{{ project.description }}</p>
        <a href="{% url 'projects:detail' project.id %}" class="btn btn-primary">Details</a>
      </div>
    </div>
  {% endfor %}

  <a href="{% url 'projects:new' %}" class="btn btn-primary">Create New Project</a>
{% endblock %}